In [4]:
import numpy as np

In [10]:
#Q2

#a
c = np.arange(6).reshape(2,3)+1
d = np.arange(8).reshape(2,4)+1
d[1,:]=np.array([4,5,6,9])
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [4 5 6 9]]


In [12]:
c.T@d

array([[17, 22, 27, 40],
       [22, 29, 36, 53],
       [27, 36, 45, 66]])

In [15]:
#Q2

#b
c = np.arange(9).reshape(3,3)+1
d = np.arange(12).reshape(4,3)+1
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
d@c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])

In [19]:
#or 
c@d.T

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

In [24]:
#Q3
a = np.arange(4).reshape(2,2)+1
print(a)

[[1 2]
 [3 4]]


In [25]:
np.insert(a,a.shape[1],np.ones(a.shape[0]), axis=1)

array([[1, 2, 1],
       [3, 4, 1]])

In [54]:
#q c
a = np.array([[1,2,3,4,2],[5,6,7,8,3],[-1,-4,-2,-5,4]]).T
print(a)

[[ 1  5 -1]
 [ 2  6 -4]
 [ 3  7 -2]
 [ 4  8 -5]
 [ 2  3  4]]


a. has 3 variables
b. 5 samples
c. (5,4)

In [55]:
 a = np.insert(a,a.shape[1],np.ones(a.shape[0]), axis=1)

In [56]:
#d 
dar = np.identity(4)
dar[0,3] = 5
dar[1,3] = -2
dar[2,3] = 0
print(dar)

[[ 1.  0.  0.  5.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [61]:
#e.
a@dar.T

array([[ 6.,  3., -1.,  1.],
       [ 7.,  4., -4.,  1.],
       [ 8.,  5., -2.,  1.],
       [ 9.,  6., -5.,  1.],
       [ 7.,  1.,  4.,  1.]])

In [64]:
#f
s = np.array([[0.5,0,0,0],[0,2,0,0],[0,0,1,0],[0,0,0,1]])
print(s)

[[0.5 0.  0.  0. ]
 [0.  2.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


In [65]:
(s@a.T).T

array([[ 0.5, 10. , -1. ,  1. ],
       [ 1. , 12. , -4. ,  1. ],
       [ 1.5, 14. , -2. ,  1. ],
       [ 2. , 16. , -5. ,  1. ],
       [ 1. ,  6. ,  4. ,  1. ]])